#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

livereload: true

url: 'http://localhost:4000'
baseurl: ''
urlassets: 'http://localhost:4000/assets/'
urlimg: 'http://localhost:4000/images/'
urlvid: 'http://localhost:4000/videos/'

# Disable when not in production
google_analytics_tracking_id:

sass:
  style: 'nested'
  sourcemap: 'never'
  line_comments: true
