---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _cities
  label: Cities
  create: all
  match: "**/*"
- type: directory
  path: _courses
  label: Courses
  create: all
  match: "**/*"
- type: directory
  path: _dances
  label: Dances
  create: all
  match: "**/*"
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: _parties
  label: Parties
  create: all
  match: "**/*"
- type: directory
  path: _teachers
  label: Teachers
  create: all
  match: "**/*"
- type: directory
  path: _archive_courses
  label: Archive courses
  create: all
  match: "**/*"
upload_dir: _images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 4000 --host localhost -d _site --config _config.yml,_config_dev.yml
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
